# Author:  Michael Jørgensen
#
# Description: Makefile for simulating the entire project

all:
	make -C tb_wbus_arbiter
	make -C tb_wbus_axi
	make -C tb_wbus_master

clean:
	make -C tb_wbus_arbiter clean
	make -C tb_wbus_axi clean
	make -C tb_wbus_master clean

